/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcceptableUseRouteImport } from './routes/acceptable-use'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as FreeTrialRouteImport } from './routes/free-trial'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LicenseRouteImport } from './routes/license'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TrialSuccessRouteImport } from './routes/trial-success'
import { Route as UseCasesRouteImport } from './routes/use-cases'
import { Route as CheckoutDurationDevicesRouteImport } from './routes/checkout.$duration.$devices'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptableUseRoute = AcceptableUseRouteImport.update({
  id: '/acceptable-use',
  path: '/acceptable-use',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeTrialRoute = FreeTrialRouteImport.update({
  id: '/free-trial',
  path: '/free-trial',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseRoute = LicenseRouteImport.update({
  id: '/license',
  path: '/license',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TrialSuccessRoute = TrialSuccessRouteImport.update({
  id: '/trial-success',
  path: '/trial-success',
  getParentRoute: () => rootRouteImport,
} as any)
const UseCasesRoute = UseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutDurationDevicesRoute = CheckoutDurationDevicesRouteImport.update({
  id: '/checkout/$duration/$devices',
  path: '/checkout/$duration/$devices',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/free-trial': typeof FreeTrialRoute
  '/how-it-works': typeof HowItWorksRoute
  '/license': typeof LicenseRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/trial-success': typeof TrialSuccessRoute
  '/use-cases': typeof UseCasesRoute
  '/checkout/$duration/$devices': typeof CheckoutDurationDevicesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/free-trial': typeof FreeTrialRoute
  '/how-it-works': typeof HowItWorksRoute
  '/license': typeof LicenseRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/trial-success': typeof TrialSuccessRoute
  '/use-cases': typeof UseCasesRoute
  '/checkout/$duration/$devices': typeof CheckoutDurationDevicesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/acceptable-use': typeof AcceptableUseRoute
  '/accessibility': typeof AccessibilityRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/faq': typeof FaqRoute
  '/features': typeof FeaturesRoute
  '/free-trial': typeof FreeTrialRoute
  '/how-it-works': typeof HowItWorksRoute
  '/license': typeof LicenseRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/terms': typeof TermsRoute
  '/trial-success': typeof TrialSuccessRoute
  '/use-cases': typeof UseCasesRoute
  '/checkout/$duration/$devices': typeof CheckoutDurationDevicesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/acceptable-use'
    | '/accessibility'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/features'
    | '/free-trial'
    | '/how-it-works'
    | '/license'
    | '/order-confirmation'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/trial-success'
    | '/use-cases'
    | '/checkout/$duration/$devices'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/acceptable-use'
    | '/accessibility'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/features'
    | '/free-trial'
    | '/how-it-works'
    | '/license'
    | '/order-confirmation'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/trial-success'
    | '/use-cases'
    | '/checkout/$duration/$devices'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/acceptable-use'
    | '/accessibility'
    | '/contact'
    | '/cookies'
    | '/faq'
    | '/features'
    | '/free-trial'
    | '/how-it-works'
    | '/license'
    | '/order-confirmation'
    | '/pricing'
    | '/privacy'
    | '/refund-policy'
    | '/terms'
    | '/trial-success'
    | '/use-cases'
    | '/checkout/$duration/$devices'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcceptableUseRoute: typeof AcceptableUseRoute
  AccessibilityRoute: typeof AccessibilityRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  FaqRoute: typeof FaqRoute
  FeaturesRoute: typeof FeaturesRoute
  FreeTrialRoute: typeof FreeTrialRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LicenseRoute: typeof LicenseRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundPolicyRoute: typeof RefundPolicyRoute
  TermsRoute: typeof TermsRoute
  TrialSuccessRoute: typeof TrialSuccessRoute
  UseCasesRoute: typeof UseCasesRoute
  CheckoutDurationDevicesRoute: typeof CheckoutDurationDevicesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/acceptable-use': {
      id: '/acceptable-use'
      path: '/acceptable-use'
      fullPath: '/acceptable-use'
      preLoaderRoute: typeof AcceptableUseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-trial': {
      id: '/free-trial'
      path: '/free-trial'
      fullPath: '/free-trial'
      preLoaderRoute: typeof FreeTrialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license': {
      id: '/license'
      path: '/license'
      fullPath: '/license'
      preLoaderRoute: typeof LicenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trial-success': {
      id: '/trial-success'
      path: '/trial-success'
      fullPath: '/trial-success'
      preLoaderRoute: typeof TrialSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/use-cases': {
      id: '/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof UseCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$duration/$devices': {
      id: '/checkout/$duration/$devices'
      path: '/checkout/$duration/$devices'
      fullPath: '/checkout/$duration/$devices'
      preLoaderRoute: typeof CheckoutDurationDevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcceptableUseRoute: AcceptableUseRoute,
  AccessibilityRoute: AccessibilityRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  FaqRoute: FaqRoute,
  FeaturesRoute: FeaturesRoute,
  FreeTrialRoute: FreeTrialRoute,
  HowItWorksRoute: HowItWorksRoute,
  LicenseRoute: LicenseRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundPolicyRoute: RefundPolicyRoute,
  TermsRoute: TermsRoute,
  TrialSuccessRoute: TrialSuccessRoute,
  UseCasesRoute: UseCasesRoute,
  CheckoutDurationDevicesRoute: CheckoutDurationDevicesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
